### PR TITLE
fix the fucking gender pronouns

### PR DESCRIPTION
**Pull request by jazzsequence**
Gender pronouns are mismatched.

### CODE REVIEW

**Comment by marktimemedia** [comment]
I actually envisioned this being someone talking about a chick's boyfriend/brother/father/male associate.

**Comment by jazzsequence** [comment]
Okay, I can see that now.

**Comment by jazzsequence** [comment]
Maybe it should be more specific? Like "Don't tell her I said this, but that dude she's with is a real..."?

**Comment by marktimemedia** [comment]
I'm down with that.

**Pull request merged**
