### PR TITLE
actually use that minfied shit

### PR DESCRIPTION
**Pull request by bradp**

### CODE REVIEW

**Comment by bradp** [comment]
ugh the other PRs broke this shit, hold on

**Comment by bradp** [comment]
k all better now

**Comment by marktimemedia** [comment]
Yeah yeah, too lazy to fucking figure out the merge conflicts, I'll do it myself locally and re-push.

**Comment by bradp** [comment]
already fixed em

**Comment by bradp** [comment]
in this VERY PR

**Comment by marktimemedia** [comment]
I know, but there were more cause I re-minified the fucking JS with other people's shit

**Pull request closed without merging**
